remove unused variable
gcc 4.6 was reporting warning:
../daemon/room_save.c:372:8: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]