daemon: fix removal of app that was loaded in stopped state
ERROR: ladish_virtualizer_is_hidden_app: Code execution taboo point. function ladish_virtualizer_is_hidden_app in ../daemon/virtualizer.c:1112