Fix -Werror=restrict
While one could be safe to assume that first input is read,
then symlink target is copied to user-mode, it causes compiler
warning.

So, don't reuse the symlink filename buffer for storing symlink
target.

../daemon/procfs.c:155:28: error: passing argument 2 to restrict-qualified parameter aliases with argument 1 [-Werror=restrict]
  155 |   ret = readlink(g_buffer, g_buffer, sizeof(g_buffer));
      |                  ~~~~~~~~  ^~~~~~~~

sys-libs/glibc-2.30-r8 (armv7a, but ISA probably does not matter)
gcc (Gentoo 9.3.0 p2) 9.3.0